### ISSUE TITLE
shops dont show on connect

### ISSUE THREAD

**Issue by BruiserX** [redyydev/ry_shops#5]
onplayer load shops are looking for the job too quickly and the shops do not show up until script is restarted.

and then it happens each time for every player that connects since shops are client side.

**Comment by redyydev** [comment]
hello, i pushed a update for the functions. Try it and say it if its solved, thank you!

**Comment by BruiserX** [comment]
Beautiful! works great now thank you so much, really loving the shop script

**Comment by redyydev** [comment]
great! If you want any help contact me on discord: redyydev
